custom:
    - "https://github.com/sponsors/statikfintechllc"
    - "https://patreon.com/StatikFinTech_LLC"
    - "https://ko-fi.com/statikfintech_llc"
    - "https://cash.app/$statikmoney8"
    - "https://paypal.me/statikmoney8"