custom:
  - "https://github.com/sponsors/statikfintechllc"
  - "https://patreon.com/StatikFinTech_LLC"
  - "https://ko-fi.com/statikfintech_llc"
  - "https://paypal.me/statikmoney8"
  - "https://cash.app/$statikmoney8"
